### ISSUE TITLE
TypeError & KeyError

### ISSUE THREAD

**Issue by ghost** [brimorlabs/KStrike#3]
Facing two issues while running KStrike, any suggestion?
I do appreciate any feedback - thanks.

**Issue 1:**
C:\>KStrike.py Current.mdb > TEST_Current.txt

Python Version3 detected

The number of tables is 8
Table 0 Name is: MSysObjects
Table 1 Name is: MSysObjectsShadow
Table 2 Name is: MSysObjids
Table 3 Name is: MSysLocales
Table 4 Name is: ROLE_ACCESS
Table 5 Name is: CLIENTS
Table 6 Name is: DNS
Table 7 Name is: VIRTUALMACHINES
The table "DNS" has zero records
Parsing 1 of 4 CLIENTS table records
Traceback (most recent call last):
  File "C:\KStrike.py", line 345, in <module>
    Check_Column_Type(Table_Record, Column_Type, x, Data_Value) #Arguments to pass to subroutine
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\KStrike.py", line 251, in Check_Column_Type
    if ( (value > 0) and ( "Day" in str(Column_Name)) ): #Checking to see if Day is in the field. If so, we will do some converting
          ^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'int'

---------------------------------------------------------

**Issue 2:**
C:\>KStrike.py SystemIdentity.mdb > TEST_SystemIdentitiy.txt

Python Version3 detected

The number of tables is 7
Table 0 Name is: MSysObjects
Table 1 Name is: MSysObjectsShadow
Table 2 Name is: MSysObjids
Table 3 Name is: MSysLocales
Traceback (most recent call last):
  File "C:\KStrike.py", line 300, in <module>
    Table_name = Table_Dict[Table.get_name()]
                 ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'SYSTEM_IDENTITY'

**Comment by brimorlabs** [comment]
Good evening,

Issue #2 is that KStrike is not written to run against SystemIdentity. You
can feel free to modify it to do so, if you wish, but, there is not really
that much information from System Identity that is terribly useful.

Issue #1 looks, to me, like there is an issue as it is looking for a value,
but it seems to be finding a 'NoneType'. That (should) not be possible, as
a value should be returned as an int, but it looks like it is not able to
decipher "what" exactly is happening. I can't say for certain without the
data, but you can put in a distinct clause to determine if the "value" is
actually None, and, if so, error out more gracefully, such as here:
https://bobbyhadz.com/blog/python-typeerror-not-supported-between-instances-of-nonetype-and-int

I've never seen that happen before as an issue, I can make the change, but
again, I have never actually seen that be an issue based off the databases
that myself, and others, have collected and parsed.


Brian


*Brian Moran *
*Digital Strategy Consultant*

Phone: 443.834.8280
Web: www.brimorlabs.com
***@***.***


*This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager.
This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. If you are not the intended recipient
you are notified that disclosing, copying, distributing or taking any
action in reliance on the contents of this information is strictly
prohibited.*

**Comment by ghost** [comment]
Hi Brian, thanks for your feedback. Good to know that SystemIdentity.mdb was not into the focus of your py script. 

To double check I used also your published .mdb files, but the error is the same. 

I started to modify the code and added following to void the error but it caused more and more problems:

 if value is not None and Column_Name is not None:
        if ( (value > 0) and ( "Day" in str(Column_Name)) ): #Checking to see if Day is in the field. If so, we will do some converting

So basically I am again at the beginning asking myself: 
its related to my environment ?

I made already the live check of the information in the .mdb files via PS but I wanted also to double check with your KStrike results.

Original Error:
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\KStrike.py", line 345, in <module>
    Check_Column_Type(Table_Record, Column_Type, x, Data_Value) #Arguments to pass to subroutine
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\KStrike.py", line 251, in Check_Column_Type
    if ( (value > 0) and ( "Day" in str(Column_Name)) ): #Checking to see if Day is in the field. If so, we will do some converting
          ^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'int'

Do you have any other suggestion what I can do to solve it?

Thanks a lot!

**Comment by ghost** [comment]
Update: 
Tested on Kali Linux 2023.2, Python 3.11.5
with your current sample.mdb -> TypeError: '>' not supported between instances of 'NoneType' and 'int'

Tested on Windows 10, 10.0.19045 Build 19045, Python 3.11.5
with your sample current.mdb -> TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by brimorlabs** [comment]
I don't know what to tell you, I just downloaded the SIFT workstation, ran
that, and the KStrike script from github, and it worked just fine for me.

Maybe it is something with a newer version of Python (it would not surprise
me if that were the case, because Python is notorious for not actually
supporting previous issues, which is why Perl is, was, and will be, the
best) but it works fine for me, and it is not something that I can
replicate.

I also checked it on my WSL instance that I configured everything on, that
is 3.10.6, and it works just fine on that as well.


*Brian Moran *
*Digital Strategy Consultant*

Phone: 443.834.8280
Web: www.brimorlabs.com
***@***.***


*This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager.
This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. If you are not the intended recipient
you are notified that disclosing, copying, distributing or taking any
action in reliance on the contents of this information is strictly
prohibited.*

**Comment by kev365** [comment]
Hi Brian!
I've been messing around with KStrike and libesedb a bit this weekend. I was looking at this error as well and found this information.

https://docs.python.org/3/whatsnew/3.0.html#ordering-comparisons

> Python 3.0 has simplified the rules for ordering comparisons:
> 
> The ordering comparison operators (<, <=, >=, >) raise a TypeError exception when the operands don’t have a meaningful natural ordering. Thus, expressions like 1 < '', 0 > None or len <= len are no longer valid, and e.g. None < None raises [TypeError](https://docs.python.org/3/library/exceptions.html#TypeError) instead of returning False. A corollary is that sorting a heterogeneous list no longer makes sense – all the elements must be comparable to each other. Note that this does not apply to the == and != operators: objects of different incomparable types always compare unequal to each other.

After reviewing this site below, which I noticed was mentioned above, too!
https://bobbyhadz.com/blog/python-typeerror-not-supported-between-instances-of-nonetype-and-int

I modified lines 251 and 276 to be:
`(value is not None)` rather than `(value > 0)`

The tool completed without additional errors. Though I'll be honest, I'm not good enough at this to know if everything worked out ok. Other than at least it may error out on Python 2? I noticed the Python 2 checks, but I'm on Python 3.

I was using the sample data provided with the script, specifically 
`\KStrike\Sample_UAL\Nondomain-User\Current.mdb`

============================================

Aside from that, for my own personal preference, 
I had modified my own line 336 from:
`DatesAndAccesses||\r\n") #This is the header`
to:
`DatesAndAccesses||\n") #This is the header`
To removed the extra line after the header

Also I modified my own line 346 from:
`sys.stdout.write("||\r\n")`
to :
`sys.stdout.write("||\n")`
to remove other extra lines.

**Comment by brimorlabs** [comment]
With the change(s) Kevin suggested, it looks like the TypeError has been resolved, so I am going to mark this closed for now. The line return (\r\n) is required on some OS/programs, but not others, so I need to try to delve into that more to see if I can figure out a one size fits all solution, but that is a separate issue than the TypeError, so I feel that marking this as closed should complete it
